- mkdocs-cn/mkdocs.yml
- mkdocs.yml
Minor update to the yaml file to trigger a build again
> minor update

- material-overrides/assets/stylesheets/moonbeam.css
- mkdocs-cn/mkdocs.yml
- mkdocs.yml
Add pop-up for when an external link is clicked that informs the user they're leaving the Moonbeam docs site and going to an independent, third party website.
This PR adds styling for the pop-up and includes the related JavaScript file in the mkdocs.yml files
> add modal for external links

- material-overrides/assets/stylesheets/moonbeam.css
> group classes with same background color

- material-overrides/assets/stylesheets/moonbeam.css
comment out unused admonitions
> comment out unused admonitions

- material-overrides/assets/stylesheets/moonbeam.css
Generic updates:
- Set the width of the page to fit content
- Font for headers should be varela round
Mobile updates:
- remove connect to metamask button
- update document dates to break into two lines
- fix spacing around disclaimers
> Mobile styling updates

- material-overrides/assets/stylesheets/moonbeam.css
Update classes for CN site for the new admonitions: challenge and remember
> update styling for cn admonitions

- material-overrides/assets/stylesheets/moonbeam.css
> add new code admonition styling

- material-overrides/assets/stylesheets/moonbeam.css
> add missing comma to note styles 

- material-overrides/assets/stylesheets/moonbeam.css
- mkdocs-cn/mkdocs.yml
- mkdocs.yml
This PR adds the kapa widget to the docs site! Let me know if you want me to change the styling of it! 🙂
> Add kapa widget to docs site!

- .github/CODEOWNERS
- mkdocs-cn/mkdocs.yml
- mkdocs.yml
- readme.md
- scripts/calculate-redirects.py
- scripts/move-pages.py
Update links from purestake to moonbeam-foundation
> remove references to purestake

- mkdocs-cn/material-overrides/404.html
- mkdocs-cn/material-overrides/partials/source-file.html
- mkdocs-cn/material-overrides/subsection-index-page.html
Deleted these template files from CN section, but they are needed for the staging site. So adding them back in
> add files back for staging

- mkdocs-cn/material-overrides/partials/feedback.html
- mkdocs-cn/material-overrides/partials/nav-item.html
- mkdocs-cn/material-overrides/partials/nav.html
- mkdocs-cn/material-overrides/partials/search.html
- mkdocs-cn/material-overrides/partials/tabs.html
We didn't previously have all the modified override files copied over to the Chinese side, but turns out we need to have all of them
> add new partial files to cn

- mkdocs-cn/mkdocs.yml
- mkdocs.yml
Add redirects for the Truffle pages that have been removed
> add truffle redirects

- material-overrides/assets/stylesheets/moonbeam.css
update shade of purple on the challenge admonition so it stands out a little bit more
> update shade of purple on the challenge admonition

- material-overrides/partials/header.html
- mkdocs-cn/material-overrides/partials/header.html
This PR updates the text for the connect metamask button to be connect wallet instead
> Update the connect wallet button

- mkdocs-cn/mkdocs.yml
- mkdocs.yml
Try using the `navigation.prune` feature to reduce the DOM size and boost performance.
> enable navigation pruning

- mkdocs-cn/mkdocs.yml
Add termynal configs for the CN site!
> add termynal for cn site

- mkdocs-cn/mkdocs.yml
- mkdocs.yml
This PR adds redirects for dtmb back to the dapps list index page
> add downtown moonbeam redirects

- mkdocs.yml
> update copyright year

- material-overrides/main.html
> Fix typo in banner

- material-overrides/main.html
update the banner for async backing coming to moonbeam and moonriver
> update the banner for async backing coming to moonbeam and moonriver

- material-overrides/assets/stylesheets/moonbeam.css
- material-overrides/partials/footer.html
- mkdocs-cn/material-overrides/partials/footer.html
This PR centers the tables and also adds a papermoon shoutout 🩵
> Center tables

- mkdocs.yml
Adds Redirect for State of the dApps
> Adds Redirect for State of the dApps

- material-overrides/partials/tabs.html
This PR aims to fix the navigation navbar items, so when you click on any nav item, you get redirected to the index page of that section
> [FIX] - Navbar navigation items

- material-overrides/main.html
New Banner for Runtime 3400 (Probably should not merge until Runtime 3400 is live) 
https://forum.moonbeam.network/t/runtime-rt3400-schedule/1954
> New Banner for Runtime 3400

- material-overrides/assets/stylesheets/moonbeam.css
- material-overrides/main.html
Add a script that ignores the keyboard shortcuts when interacting with Kapa
> add script to enable use of any keys when interacting with kapa

- redirects.json
> Add DappRadar Redirects

- material-overrides/assets/stylesheets/timeline-neoteroi.css
- mkdocs.yml
- requirements.txt
This PR adds the timeline element to the docs site. The CSS file is an empty placeholder, which I will complete under a separate PR.
> adds timeline element with placeholder css file

- material-overrides/assets/stylesheets/moonbeam.css
I added the CSS styles for the cookbook button and removed some space to accommodate the button, as in regions outside the US the buttons have shorter text.
> Update style for the cookbook button

- material-overrides/assets/stylesheets/moonbeam.css
- material-overrides/partials/header.html
This PR removes the logic and styles for the ASK IA button in the header.
> Cookbook Fix

- material-overrides/assets/stylesheets/moonbeam.css
- material-overrides/main.html
- material-overrides/partials/footer.html
- mkdocs.yml
Footer
- Adds button to footer for copying llm-full.txt to the user clipboard with script for functionality 
- Adds styling to convert the footer to a three-column layout. Feel free to play with this if you hate it. hahaha
- Random side quest: updated the year to 2025 for the copyright
Use this branch from moonbeam-docs to view: https://github.com/moonbeam-foundation/moonbeam-docs/pull/1122
> make LLMs accessible from a single button

- mkdocs-cn/material-overrides/partials/header.html
In this PR, I have updated the `header.html` from the cn-docs to match the distribution of the `header.html` in the en-docs version.
> Update the cn-docs header

- material-overrides/assets/stylesheets/moonbeam.css
- material-overrides/partials/footer.html
I added a breakpoint for larger screens to limit the size of the header, footer, and cookie consent.
> Responsive Fix

- material-overrides/home.html
- mkdocs.yml
This PR fixes a 404 error. I also added the routes for the missing scripts to the YML file to utilize the minify plugin, addressing some unminified issues.
This PR needs to be merged together with this one:  https://github.com/moonbeam-foundation/moonbeam-docs/pull/1140
> Semrush SEO Report - May

- redirects.json
This PR removes the index from the routes in the redirects
> Remove index from the redirects
