papermoonio/moonbeam-mkdocs

material-overrides/assets/stylesheets/moonbeam.css, mkdocs-cn/mkdocs.yml, mkdocs.yml
Adds the feedback widget to the docs site. The feedback (smiley or frown) can be viewed from the google analytics dashboard. If a user wants to provide additional feedback as to what can be improved, they are directed to create an issue on github.
Goes with EN PR: https://github.com/PureStake/moonbeam-docs/pull/570
Goes with CN PR: https://github.com/PureStake/moonbeam-docs-cn/pull/237
=> add feedback widget to docs site

material-overrides/assets/stylesheets/moonbeam.css, material-overrides/home.html, mkdocs-cn/material-overrides/home.html
Add some additional breakpoints so that the home page looks better on various size screens. Had to do some trickery to make this possible because the HTML elements are initially in columns, so I had to move some elements out of the column format at certain points, hence why the `row hero-buttons-small` and `row quick-refs-medium` divs are required
This also fixes the external links modal to look good on all screens.
=> add additional home page break points and fix width of the external link pop-up

material-overrides/assets/stylesheets/moonbeam.css, material-overrides/partials/source-file.html, mkdocs-cn/mkdocs.yml, mkdocs.yml, requirements.txt
Add a feature that puts the last updated and created dates on each page. Tried to remove on the section index pages, but there is no easy way to do so. I don't think it looks terrible but not entirely necessary 🤷‍♀️ 
There is an issue with a handful of pages where the plugin cannot find the date a page was created and it automatically defaults to the current date. So, I created a script that checks the dates on each page and if the created date is after the updated date, it renders the updated date as the created date instead.
Goes with: https://github.com/PureStake/moonbeam-docs/pull/597
=> Add document dates feature

material-overrides/assets/stylesheets/moonbeam.css
I noticed on Friday that content pages weren't rendering correctly but the home page and index pages were rendered perfectly fine. So `fit-content` won't work as a general fix. So I dug a bit deeper and realized that the `.md-header-nav__*` classes were removed and replaced with `.md-header__*` classes at some point and this wasn't caught when I updated the dependencies. So this was causing issues with the top navigation where the width of the nav was smaller than the width of all of the elements combined for small screens (not all mobile devices, but some). Which caused the screen to widen and a horizontal scrollbar to appear and the  language dropdown to hang off the edge.
Previously, the solution was to get rid of the title on the home page, but I noticed that on all of the index pages …
=> Fix navigation

material-overrides/assets/stylesheets/moonbeam.css, material-overrides/main-index-page.html, material-overrides/subsection-index-page.html, mkdocs-cn/material-overrides/main-index-page.html, mkdocs-cn/material-overrides/subsection-index-page.html, mkdocs-cn/mkdocs.yml, mkdocs.yml
This PR adds two templates for the index pages:
1) For main index pages i.e., Builders, Node Operators, Learn, etc.
2) For all other ("subsection") index pages
The main differences being that the main index pages include disclaimers that the subsection index pages don't and the subsection index pages contain logic to dive deeper to generate index pages for nested directories
It also removes the old script for rendering subsections.
Goes with PRs: 
- EN: https://github.com/PureStake/moonbeam-docs/pull/606
- CN: https://github.com/PureStake/moonbeam-docs-cn/pull/262
=> Add templates for index pages

material-overrides/subsection-index-page.html, mkdocs-cn/material-overrides/subsection-index-page.html
Update logic for editing the links to the subsection's pages vs the href links to the icons.
For example, take a look at this URL: `/builders/interoperability/xcm/xcm-transactor/#xcmtransactor-precompile`
- the `image_path` was correct and was rendered as `/images/index-pages/builders/interoperability/xcm/xcm-transactor.png`
- the `subsection_path` was changed to `builders/interoperability/xcm/xcm-transactor/`, which means the path wasn't relative and the link to the `#xcmtransactor-precompile` section was lost and so the final path ended up being `/builders/pallets-precompiles/precompiles/builders/interoperability/xcm/xcm-transactor/`
This PR changes it so that the `image_path`s are updated only and the `subsection_path`s are not unnecessarily modified
=> edit logic for getting link to pages vs icon hrefs

mkdocs-cn/mkdocs.yml, mkdocs.yml
Add redirects for the removed boba pages back to the networks index page
=> update redirects from removing boba docs

material-overrides/assets/stylesheets/moonbeam.css
When implementing the docs site redesign, I checked Chrome and Firefox, but never checked Safari. There were a couple issues on Safari: one with positioning of the dropdown menus and another with the social icons not appearing. This PR fixes both. I double-checked the changes on Chrome and Firefox to ensure everything looks as it should 🙂
=> update css for safari

material-overrides/assets/stylesheets/moonbeam.css
Update styling for text in tabs, so there is a slight margin around the text. Also remove some commented out styles that aren't needed
=> add styling for text and lists in tabs

mkdocs.yml, readme.md
This PR adds the `enabled` config to the git-revision-date-localized plugin so that it can be disabled on local development. @albertov19 you're on windows, right? can you test this out? depending on what terminal you use, you may need to set the variable differently
windows command prompt: `set ENABLED_GIT_REVISION_DATE=false`
windows powershell: `$env:ENABLED_GIT_REVISION_DATE = "false"`
let me know I can update the readme!
=> add config to disable the git-revision-date-localized plugin

mkdocs-cn/mkdocs.yml, mkdocs.yml
Add redirects for the removed mintable XC-20 pages. It'll take users back to the XC-20 Overview page where they can check out the types of XC-20s.
Page removed in: https://github.com/moonbeam-foundation/moonbeam-docs/pull/788 and https://github.com/moonbeam-foundation/moonbeam-docs-cn/pull/358
=> add mintable xc20 redirect

material-overrides/assets/stylesheets/termynal.css, mkdocs.yml
This PR adds termynal to the docs site. This should be used moving forward as a consistent and easy-to-maintain alternative to taking screenshots of the terminal.
=> add termynal

material-overrides/assets/stylesheets/termynal.css
This PR applies the same changes we made in the Tanssi repo. It separates the system name (`moonbeam@ubuntu-jammy`) and the file path (`~$`) 
Goes with this PR: https://github.com/moonbeam-foundation/moonbeam-docs/pull/846
=> update termynal css

material-overrides/assets/stylesheets/moonbeam.css, mkdocs-cn/material-overrides/partials/tabs.html
This PR updates the styling for the left nav, so the nav items aren't jumping left and right when active or on hover.
It also applies a minor fix to the CN site for the dropdown icons so it renders the new webp icons
=> Update nav styling

mkdocs-cn/mkdocs.yml, mkdocs.yml
We're not using any of the termynal animations, and, for the sake of performance, we don't need to either. So this PR removes the extra unnecessary JavaScript file.
Goes with: https://github.com/moonbeam-foundation/moonbeam-docs/pull/856
=> remove termynal js

material-overrides/assets/stylesheets/moonbeam.css, mkdocs-cn/mkdocs.yml, mkdocs.yml
This PR fixes two things:
1. The right-hand side table of contents shifts when you click on or scroll down a page; whatever section is the active section, it shifts to the right, so it looks like its subsection when it is not. For example, the [pre-funded development accounts section](https://docs.moonbeam.network/builders/get-started/networks/moonbeam-dev/#pre-funded-development-accounts) is a main section (##) not a subsection (###)
2. Just realized that we do use emojis on the [Source Code page](https://docs.moonbeam.network/learn/platform/code/), which was an oversight on my part, as I just removed this functionality in the last dependency update 🙈
=> Fix the TOC shifting and emoji rendering

mkdocs-cn/mkdocs.yml, mkdocs.yml
This PR removes the init kapa script from the minify list. it's already been removed from the `extra_javascript` config, so just needs to be removed here too!
EDIT: this PR also removes the privacy plugin temporarily. there are some compatibility issues with some of the other changes i was making that didn't get tested and as a result broke some stuff. so I need to circle back to that later
=> remove kapa widget script from minify list and temporarily disable the privacy plugin

material-overrides/assets/stylesheets/termynal.css
This is so the text within the terminal doesn't overflow outside of the window.
=> update termynal styling to break long lines to the next line

material-overrides/assets/stylesheets/moonbeam.css
add styling to prevent code blocks from overlapping the Copy to Clipboard button
check out the tanssi PR for an example of the change: https://github.com/papermoonio/tanssi-mkdocs/pull/26
=> update code block styling

material-overrides/assets/stylesheets/moonbeam.css
Make the intro disclaimer text slightly smaller
Before:
After:
Note: the `*`s won't be there as they are displayed on the After image so please ignore those 😅
=> make intro disclaimer text slightly smaller

material-overrides/assets/stylesheets/moonbeam.css, material-overrides/main.html, mkdocs.yml
This PR adds a banner feature to the top of the page on the docs site. I've set it up to include info on async backing and 6 second block times on moonbase alpha!
The link corresponds to a new page, which is under review in a separate PR (https://github.com/moonbeam-foundation/moonbeam-docs/pull/877)
=> add banner feature and info about async backing

material-overrides/home.html
This PR applies a minor fix to improve the LCP on the home page by preloading the hero image. Tests show that this boosts the LCP by .3 seconds on average.
=> preload the hero image on the home page

material-overrides/main.html
On the live site right now, if you open the terminal, you'll see 404 errors for `moonbeam.css`. This PR fixes that by removing `moonbeam.css` from the `main.html` file. The `moonbeam.css` file gets pulled in from the `mkdocs.yml` file now (along with the `termynal.css` file.
Test this locally and with the `build-docs-site` repo
=> Fix moonbeam.css 404 issue

material-overrides/main.html, mkdocs.yml
This PR updates the async backing banner link to point to the overview of runtime 2800 on the Moonbeam Forum, which goes over some of the details of async backing. It also adds a redirect for the Runtime 2800 page that links back to the Moonbeam Forum page.
Goes with: https://github.com/moonbeam-foundation/moonbeam-docs/pull/890
=> update banner link and add redirect for runtime 2800 page

readme.md
Add a section to the readme on using the `--dirty` flag when running the docs site locally. This is a big time saver in general, especially when frequently making and updating small changes
=> add info on dirty builds

material-overrides/assets/stylesheets/termynal.css
This makes it so that whitespacing is preserved
Before:
After:
=> preserve whitespace in termynal snippets

scripts/internal-links.py
This PR adds a script to make sure that all internal links have backslashes at the end of them (except images and those with a "#" in the link, indicating that there is a section that is being referenced)
=> add script to update internal links

material-overrides/assets/stylesheets/moonbeam.css
This just fixes the copyright section of the footer on smaller screens
(ignore my browser console at the bottom of the screenshot)
=> fix copyright section

material-overrides/main.html
Update banner messaging now that 6s block times are here on Moonriver!
=> update the banner messaging for async backing on Moonriver

material-overrides/main.html
This PR updates the async backing banner so it's applicable for all moonbeam networks
=> update banner - async backing for all networks

mkdocs-cn/mkdocs.yml
Adding language specification for chinese mkdoc.
This translates site elements such as: "search", "Next", "Prev" etc.
=> Adding chinese support for website elements

material-overrides/assets/stylesheets/moonbeam.css
The previous border color wasn't showing up. So, this just adds the default border between the title and the code snippet.
=> update styling for code titles

material-overrides/subsection-index-page.html, mkdocs.yml
Add redirects for the XCM SDK docs and manually provide a description to be rendered on the XCM Interoperability index page, since it can no longer be automatically generated in the same way as before.
=> add xcm sdk redirects

mkdocs.yml
We had two pages for runtime upgrades and historical updates, so I deleted the duplicate pages in this PR: https://github.com/moonbeam-foundation/moonbeam-docs/pull/993
So, this PR just redirects the duplicate to the remaining pages
=> add redirects for historical updates and runtime upgrades

material-overrides/home.html, scripts/calculate-redirects.py, scripts/update-internal-links.py
This PR includes some updates to links on the home page that were causing some warnings to pop up in the SEO report. It also includes a new script that can be used to fix links throughout the docs site and add `/` at the end of the links. Would like to maybe add this as a pre-commit hook or something more automated at some point but this is a quick win for now
=> Updates from SEO report

requirements.txt
The kluster.ai project requires the mkdocs-jupyter plugin. Since mkdocs requirements are deployed globally and affect all other mkdocs projects on the server, the requirements.txt files for all other projects must include this plugin as well.
=> Added mkdocs-jupyter to requirements.txt 

requirements.txt
Updated Pillow to version 11.1 for compatibility with Python 3.13.
This Pillow version is compatible for 3.9<= Python <=3.13 .
=> Pillow update

material-overrides/assets/stylesheets/moonbeam.css, material-overrides/partials/header.html, mkdocs.yml
This PR does the following:
- Removes `navigation.instant` because there are some issues that it causes with loading JavaScript on each page
- Update the git-revision-date-localized plugin config so that when you use the `ENABLED_GIT_REVISION_DATE` variable, it actually works and disables the plugin
- The top nav bar was moving a bit depending on whether or not the page had a corresponding CN page. So this moves the language selector to the end and uses opacity to hide and show it so that the width of the button remains in-tact and the shifting no longer occurs
=> Update mkdocs configs and fix moving nav bar

material-overrides/assets/stylesheets/moonbeam.css
This removes the box shadow under the root-level section on the left nav.
Before:
After:
=> remove box shadow

material-overrides/main.html
Add a fail-safe script that prevents shortcuts when using the cookbook, especially when typing specific letters like n, f, or p.
=> Add cookbook keyboard shortcut fail-safe

material-overrides/assets/stylesheets/moonbeam.css, material-overrides/partials/header.html
I added the logic in `header.html` to create a new div that serves as a target for placing the cookbook button next to the search button. Then, I added the CSS styles to maintain the size of the header.
=> Update cookbook styling
